/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bag.parkinggaragepos;


import filesystem.AbstractFileServiceFactory;
import filesystem.FileService;
import java.awt.Dialog;
import java.io.IOException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;

/**
 *This class is designed to be the main interface that a garage customer
 * sees. It is simply a check in and check out interface.
 * @author Ben
 */
public class CheckInGUI extends javax.swing.JFrame {
    Garage garage = null;
    JFrame mainWindow = null;
   
    /**
     * This constructor attempts to create an instance of a Garage and
     * populate a jTextArea with previous data from a data file.
     * @param mainWindow - The window that called this frame. 
     */
    public CheckInGUI(JFrame mainWindow) {
        this.mainWindow = mainWindow;
        try {
            garage = AbstractGarageFactory.getGarageInstance();
        } catch (IOException ioe) {
            JOptionPane.showMessageDialog(rootPane, ioe.getMessage());
        } catch(InvalidConfigException ice){
            JOptionPane.showMessageDialog(rootPane, ice.getMessage());
        }
        
        initComponents();
        try {
            txtOutput.append(garage.readDataContentsAndOutput());
        } catch (IOException ioe) {
            JOptionPane.showMessageDialog(rootPane, ioe.getMessage());
        }
        
        this.setGUILook();
        
    }

    /**
     * This method attempts to get the the Look and Feel of the
     * users system and assign that to this JFrame
     */
    private void setGUILook(){
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        } catch (InstantiationException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        } catch (IllegalAccessException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCheckIn = new javax.swing.JButton();
        btnCheckOut = new javax.swing.JButton();
        txtCarID = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea("Car ID\t\tHours\t\tFee\n"
            + "-----------------------------------\n");
        lblDailyCarLog = new javax.swing.JLabel();
        lblDailyCalculation = new javax.swing.JLabel();
        txtHours = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(500, 200, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        btnCheckIn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCheckIn.setText("Check In");
        btnCheckIn.setDefaultCapable(false);
        btnCheckIn.setFocusCycleRoot(true);
        btnCheckIn.setNextFocusableComponent(txtCarID);
        btnCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckInActionPerformed(evt);
            }
        });

        btnCheckOut.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCheckOut.setText("Check Out");
        btnCheckOut.setEnabled(false);
        btnCheckOut.setNextFocusableComponent(txtCarID);
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });

        txtCarID.setNextFocusableComponent(txtHours);
        txtCarID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCarIDKeyTyped(evt);
            }
        });

        jScrollPane2.setEnabled(false);
        jScrollPane2.setFocusable(false);

        txtOutput.setColumns(20);
        txtOutput.setRows(5);
        txtOutput.setEnabled(false);
        jScrollPane2.setViewportView(txtOutput);

        lblDailyCarLog.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDailyCarLog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDailyCarLog.setText("Daily car log");

        lblDailyCalculation.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDailyCalculation.setForeground(new java.awt.Color(0, 0, 255));
        lblDailyCalculation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtHours.setNextFocusableComponent(btnCheckOut);
        txtHours.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHoursKeyPressed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Car ID");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Hours");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCarID)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtHours, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDailyCarLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                    .addComponent(lblDailyCalculation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDailyCarLog)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 28, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCarID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHours, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDailyCalculation, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method checks the car into the system. It also alerts the user as to what their car id is
     * for when they checkout.
     * @param evt 
     */
    private void btnCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckInActionPerformed
        try {
            garage.checkCarIn();
        } catch (IOException ioe) {
            JOptionPane.showMessageDialog(rootPane, ioe.getMessage());
        }catch(RuntimeException rte){
            JOptionPane.showMessageDialog(rootPane, rte.getMessage());
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
        
        try{
            int ticketNumber = garage.getTicketNumber();
            JOptionPane.showMessageDialog(null, "Your ticket number for checkout is: " + ticketNumber
                    ,"Your Ticket Number: ",JOptionPane.INFORMATION_MESSAGE);
        }
        catch(IOException ioe){
            JOptionPane.showMessageDialog(null, ioe.getMessage());
        }
        btnCheckOut.setEnabled(true);
        
       
    }//GEN-LAST:event_btnCheckInActionPerformed

    
    /**
     * This method attempts to read information from the car id textbox and the 
     * hours text box in order to check out a car, as well as write data to the jTextArea.
     * @param evt 
     */
    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
        
        int carID = Integer.parseInt(txtCarID.getText());
        double hours = Double.parseDouble(txtHours.getText());
        try{
            txtOutput.append(garage.checkCarOut(carID, hours));
        }catch(IllegalArgumentException iae){
            JOptionPane.showMessageDialog(rootPane, iae.getMessage(), "Invalid input", JOptionPane.ERROR_MESSAGE);
        }
        lblDailyCalculation.setText(garage.getTotalHoursAndFees());
        txtCarID.setText("");
        txtHours.setText("");
        
    }//GEN-LAST:event_btnCheckOutActionPerformed

    /**
     * This method allows the checkout method to be called
     * by pressing the enter key on the keyboard
     * @param evt 
     */
    private void txtCarIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCarIDKeyTyped
        if(evt.getKeyChar() == '\n'){
            this.btnCheckOutActionPerformed(null);
        }
    }//GEN-LAST:event_txtCarIDKeyTyped

    /**
     * This method allows the checkout method to be called
     * by pressing the enter key on the keyboard
     * @param evt 
     */
    private void txtHoursKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoursKeyPressed
        if(evt.getKeyChar() == '\n'){
            this.btnCheckOutActionPerformed(null);
        }
    }//GEN-LAST:event_txtHoursKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckIn;
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDailyCalculation;
    private javax.swing.JLabel lblDailyCarLog;
    private javax.swing.JTextField txtCarID;
    private javax.swing.JTextField txtHours;
    private javax.swing.JTextArea txtOutput;
    // End of variables declaration//GEN-END:variables
}
